import type { Persona, InterviewResponse, PersonaScore, InsightSummary, LaunchBrief } from "@/lib/schemas";

export const fintechPersonas: Persona[] = [
  {
    id: "p1", name: "Jake Morrison", ageRange: "19-22", role: "Sophomore, part-time barista",
    incomeBand: "low", educationBand: "Some college",
    goals: ["Stop overdrawing my account", "Save for a trip", "Understand where my money goes"],
    frustrations: ["Surprise fees", "No idea what I spend on", "Budgeting apps are overwhelming"],
    toolsCurrentlyUsed: ["Venmo", "Apple Pay", "Bank's basic app"],
    buyingBehavior: "Will try free apps, skeptical of subscriptions",
    objections: ["Already broke, can't pay for an app", "Don't trust apps with bank info"],
    preferredChannels: ["TikTok", "Reddit", "Instagram"],
    quoteSnippets: ["I get paid Friday and I'm broke by Wednesday", "If it could just tell me to stop ordering DoorDash, that'd help"],
  },
  {
    id: "p2", name: "Maria Santos", ageRange: "20-23", role: "Senior, student loan anxiety",
    incomeBand: "low", educationBand: "Bachelors",
    goals: ["Build an emergency fund", "Understand student loan repayment", "Start investing"],
    frustrations: ["Too many accounts to track", "Confusing financial jargon", "No idea how to start investing"],
    toolsCurrentlyUsed: ["Mint", "Chase app", "Robinhood"],
    buyingBehavior: "Researches heavily, reads reviews before downloading",
    objections: ["Mint already does this", "Worried about hidden fees"],
    preferredChannels: ["YouTube", "Reddit", "Twitter"],
    quoteSnippets: ["I want to invest but I'm terrified of losing money", "Show me the numbers in plain English"],
  },
  {
    id: "p3", name: "DeShawn Williams", ageRange: "21-24", role: "Recent grad, first real job",
    incomeBand: "medium", educationBand: "Bachelors",
    goals: ["Build credit", "Pay off student loans fast", "Start saving for a car"],
    frustrations: ["Salary feels smaller than expected", "Student loan payments are confusing", "No guidance on credit building"],
    toolsCurrentlyUsed: ["Zelle", "Credit Karma", "Google Sheets"],
    buyingBehavior: "Willing to pay if it helps build credit faster",
    objections: ["Don't want another banking app", "Scared of credit cards"],
    preferredChannels: ["Twitter", "YouTube", "Instagram"],
    quoteSnippets: ["Nobody taught me about money growing up", "If this app can teach me credit, I'm in"],
  },
  {
    id: "p4", name: "Emma Kowalski", ageRange: "19-21", role: "Junior, impulse spender",
    incomeBand: "low", educationBand: "Some college",
    goals: ["Stop impulse buying", "Save for study abroad", "Feel financially independent"],
    frustrations: ["Can't resist sales", "No self-discipline with money", "Parents monitor her spending"],
    toolsCurrentlyUsed: ["Cash App", "Amazon", "Target Circle"],
    buyingBehavior: "Downloaded and deleted 5 budgeting apps",
    objections: ["Tried budgeting apps before, quit after a week", "Don't trust apps with money"],
    preferredChannels: ["TikTok", "Snapchat", "Instagram"],
    quoteSnippets: ["I know I spend too much, I just can't stop", "Make it like a game and maybe I'll stick with it"],
  },
  {
    id: "p5", name: "Raj Patel", ageRange: "22-25", role: "Grad student, frugal by necessity",
    incomeBand: "low", educationBand: "Masters",
    goals: ["Stretch my stipend", "Avoid more student debt", "Build emergency fund"],
    frustrations: ["Stipend barely covers rent", "No time for a side job", "Financial stress affecting studies"],
    toolsCurrentlyUsed: ["YNAB trial", "Excel spreadsheet", "Venmo"],
    buyingBehavior: "Will pay for something that actually saves money",
    objections: ["Can't justify $14/mo for YNAB", "Free tools should work"],
    preferredChannels: ["Reddit", "WhatsApp groups", "YouTube"],
    quoteSnippets: ["Every dollar counts when you're on a stipend", "If it saves me more than it costs, worth it"],
  },
  {
    id: "p6", name: "Aisha Johnson", ageRange: "18-20", role: "Freshman, first time managing money",
    incomeBand: "low", educationBand: "Some college",
    goals: ["Learn to budget", "Not rely on parents", "Save for a laptop"],
    frustrations: ["Overwhelming to manage money alone", "Parents still controlling finances", "No financial literacy education"],
    toolsCurrentlyUsed: ["Cash App", "Parent's bank account"],
    buyingBehavior: "Follows friends' recommendations blindly",
    objections: ["Parents handle my money", "Too young to need this"],
    preferredChannels: ["TikTok", "Snapchat", "Discord"],
    quoteSnippets: ["My parents still give me an allowance at 18", "I want to figure this out myself"],
  },
  {
    id: "p7", name: "Chris Nguyen", ageRange: "23-26", role: "First job, lifestyle creep",
    incomeBand: "medium", educationBand: "Bachelors",
    goals: ["Keep spending in check", "Save for a house", "Invest consistently"],
    frustrations: ["Lifestyle creep is real", "No idea how to start investing", "Too many subscription services"],
    toolsCurrentlyUsed: ["Mint", "Fidelity", "Venmo"],
    buyingBehavior: "Will pay premium for comprehensive tool",
    objections: ["Mint is free, why switch?", "Don't need another finance app"],
    preferredChannels: ["Reddit", "YouTube", "Twitter"],
    quoteSnippets: ["I make decent money but have nothing to show for it", "Just tell me what to invest in"],
  },
  {
    id: "p8", name: "Tyler Brooks", ageRange: "20-22", role: "Junior, gig economy worker",
    incomeBand: "medium", educationBand: "Some college",
    goals: ["Manage irregular income", "Pay taxes properly", "Build credit"],
    frustrations: ["Income varies wildly", "No employer benefits", "Tax season is a nightmare"],
    toolsCurrentlyUsed: ["PayPal", "Cash App", "TurboTax"],
    buyingBehavior: "Needs proof it handles irregular income",
    objections: ["Most budgeting apps assume steady paycheck", "Can't afford surprises"],
    preferredChannels: ["YouTube", "Reddit", "TikTok"],
    quoteSnippets: ["I make $800 one week and $200 the next", "Budgeting apps don't get gig life"],
  },
];

export const fintechInterviews: InterviewResponse[] = fintechPersonas.map((p) => ({
  personaId: p.id,
  reactions: ["Finally something for students like me", "Sounds useful but I've been burned before"],
  objections: (Array.isArray(p.objections) ? p.objections : [p.objections]).slice(0, 2),
  desiredFeatures: ["Bill split with roommates", "Spending alerts", "Savings challenges", "Credit score tracking"],
  trustConcerns: ["Bank-level security", "Won't sell my data", "FDIC insured?"],
  buyingTriggers: ["Free tier", "Friend recommendation", "Proven savings results"],
  switchingBarriers: ["Already using Mint/YNAB", "Don't want to connect bank", "Past app failures"],
  transcript: [
    { question: "What's your biggest money challenge?", answer: p.frustrations[0] },
    { question: "How do you currently manage finances?", answer: `Mostly ${p.toolsCurrentlyUsed[0]}` },
    { question: "Would you pay for a better tool?", answer: p.incomeBand === "high" ? "Yes, if it works" : "Only if it's free or saves me money" },
    { question: "What would make you switch?", answer: "See friends getting results first" },
  ],
}));

export const fintechScores: PersonaScore[] = fintechPersonas.map((p, i) => ({
  personaId: p.id,
  diversityScore: 0.76 + (i * 0.03),
  realismScore: 0.80 + (i * 0.02),
  uniquenessScore: 0.74 + (i * 0.03),
  overallScore: 0.77 + (i * 0.025),
}));

export const fintechInsights: InsightSummary = {
  segmentClusters: [
    {
      id: "seg_1", name: "Struggling Survivors",
      personaIds: ["p1", "p6", "p5"],
      sharedPains: ["Income barely covers expenses", "No financial literacy", "Overwhelmed by options"],
      sharedDesires: ["Simple budgeting", "Stop overdrafting", "Feel in control"],
      avgWillingnessToPay: "Free only",
      channelPreference: ["TikTok", "Reddit"],
    },
    {
      id: "seg_2", name: "Aspiring Builders",
      personaIds: ["p2", "p3", "p7"],
      sharedPains: ["Want to invest but don't know how", "Student loans", "Lifestyle creep"],
      sharedDesires: ["Build wealth", "Credit building", "Automated savings"],
      avgWillingnessToPay: "Moderate ($5-10/mo)",
      channelPreference: ["YouTube", "Twitter", "Reddit"],
    },
    {
      id: "seg_3", name: "Gig & Irregular Earners",
      personaIds: ["p4", "p8"],
      sharedPains: ["Irregular income", "Impulse spending", "Tax anxiety"],
      sharedDesires: ["Flexible budgeting", "Income smoothing", "Tax prep help"],
      avgWillingnessToPay: "Low ($3-5/mo)",
      channelPreference: ["TikTok", "YouTube"],
    },
  ],
  topPains: [
    "No idea where my money goes each month",
    "Overdraft and surprise fees",
    "Budgeting apps feel overwhelming and restrictive",
    "Can't save consistently",
    "Student loan repayment is confusing",
  ],
  topDesires: [
    "Simple, visual spending overview",
    "Automatic savings that I don't notice",
    "Bill split with roommates",
    "Credit score tracking",
    "Spending alerts before I overdraft",
  ],
  topFeatureRequests: [
    "Real-time spending notifications",
    "Bill split with friends",
    "Round-up savings",
    "Subscription tracker",
    "No-fee overdraft protection",
  ],
  pricingInsights: [
    { tier: "Free", segment: "Struggling Survivors", willingness: "High", sensitivity: "Must be free" },
    { tier: "$4.99/mo", segment: "Gig Workers", willingness: "Medium", sensitivity: "Needs to save me more than it costs" },
    { tier: "$9.99/mo", segment: "Aspiring Builders", willingness: "Medium", sensitivity: "Compare to Mint (free)" },
  ],
  positioningIdeas: [
    "The budgeting app that gets college life",
    "Stop living paycheck to paycheck, start building wealth",
    "Your money on autopilot — split bills, save smarter, no fees",
  ],
  launchRecommendations: [
    "Launch on college campuses with ambassador program",
    "Partner with personal finance TikTok creators",
    "Offer campus-specific challenges (e.g., 'No-Spend Week')",
    "Create viral 'Where did my money go?' campaign",
    "Target r/personalfinance and r/college with value-first posts",
  ],
  messagingHooks: [
    "Stop being broke by Wednesday",
    "Your money, actually under control",
    "Split the rent, save for the trip, no stress",
    "Budgeting that doesn't suck",
  ],
  objectionThemes: [
    {
      theme: "App Fatigue",
      frequency: 5,
      severity: "high",
      segments: ["Struggling Survivors", "Aspiring Builders"],
      sampleQuotes: ["I've downloaded and deleted 5 budgeting apps", "Mint already does this"],
    },
    {
      theme: "Privacy & Security",
      frequency: 4,
      severity: "medium",
      segments: ["Struggling Survivors", "Gig Workers"],
      sampleQuotes: ["I don't trust apps with my bank login", "What if my data gets leaked?"],
    },
  ],
};

export const fintechBrief: LaunchBrief = {
  targetUsers: "College students aged 18-24 who struggle to manage money on tight budgets. Primary: freshmen and sophomores managing money independently for the first time. Secondary: recent graduates navigating student loans and irregular gig income.",
  problemSolutionFit: "Most budgeting apps assume steady income and financial literacy that college students don't have. This app meets students where they are — simple visual budgeting, bill splitting, spending alerts, and gamified savings that work with irregular part-time income.",
  riskyAssumptions: [
    "Students will connect their bank account to a new app",
    "Free tier is enough to retain users long-term",
    "Gamification actually improves financial habits",
    "Students trust a startup with their financial data",
  ],
  messagingRecommendations: [
    "Lead with pain: 'Stop being broke by Wednesday'",
    "Use humor and relatability — college money stress is universal",
    "Show before/after: 'I saved $400 in one semester'",
    "Emphasize no fees and bank-level security",
  ],
  gtmSuggestions: [
    "Partner with 20 campus ambassadors at target universities",
    "Launch on r/college and r/personalfinance with value-first content",
    "Create 'No-Spend November' challenge on TikTok",
    "Collaborate with student housing for bill-split feature launch",
    "Offer referral bonus: invite 3 friends, get 3 months premium free",
  ],
  mvpFeaturePriority: [
    "Real-time spending alerts",
    "Bill split with roommates",
    "Visual budget dashboard",
    "Round-up savings",
    "Subscription tracker",
  ],
};
